/*
 * FOX NATION DASHBOARD — DATA
 * -----------------------------------------------------------------
 * EVENTS: manual snapshot pulled from the Airtable "NATION AIR TABLE"
 *   (appYVkKcbQKscED3w) as of 2026-08-21. Update this array by hand
 *   whenever the Airtable calendar changes — just add/edit/remove
 *   objects below. Each event: { date: "YYYY-MM-DD", title, category, time? }
 *
 * PTO: seed/fallback data parsed from the "2026 DOPS MGMT PTO & Event
 *   Calendar" Google Sheet. If PTO_CSV_URL (see config.js) is set to a
 *   published-to-web CSV link, the live sheet data will be fetched and
 *   this seed is only used as a fallback / before that link is set up.
 * -----------------------------------------------------------------
 */

const SEED_EVENTS = [
  { date: "2026-07-27", title: "VOD: TPUSA: Make Heaven Crowded Tour- Anchorage, AK", category: "Fox Nation" },
  { date: "2026-07-27", title: "9:00am: Lindsay Clancy Trial", category: "Live Stream" },
  { date: "2026-07-27", title: "11:50am: Pres Trump departs for Michigan", category: "Live Stream" },
  { date: "2026-07-27", title: "2:50pm: The President delivers remarks at General Motors", category: "Live Stream" },
  { date: "2026-07-27", title: "1:55pm: The President views a Drag Race and Vehicle Demonstration in Milford, MI", category: "Live Stream" },
  { date: "2026-07-27", title: "2:10pm: The President participates in a Tour and Gift Ceremony in Milford, MI", category: "Live Stream" },
  { date: "2026-07-28", title: "9:30am: Lindsay Graham Memorial in Capitol Rotunda", category: "Live Stream" },
  { date: "2026-07-28", title: "2:00pm: Lindsay Graham Funeral at Washington Cathedral", category: "Live Stream" },
  { date: "2026-07-28", title: "TBD 9:30am: The President participates in a meeting with President Zelenskyy of Ukraine", category: "Live Stream" },
  { date: "2026-07-28", title: "TBD 11:00am: The Presidents participates in a meeting with Israeli Prime Minister Benjamin Netanyahu", category: "Live Stream" },
  { date: "2026-07-28", title: "6:30pm: Senate Confirmation Vote Jay Clayton DNI", category: "Live Stream" },
  { date: "2026-07-28", title: "VOD A F&F Interview with Pres Trump", category: "Fox Nation" },
  { date: "2026-07-28", title: "A Sean Hannity Interview with Netanyahu", category: "Fox Nation" },
  { date: "2026-07-28", title: "A Sean Hannity Interview with Zelenskyy", category: "Fox Nation" },
  { date: "2026-07-29", title: "10:45am: Lindsay Graham Funeral in South Carolina", category: "Live Stream" },
  { date: "2026-07-29", title: "8:30am: Senate Hearing: Fauci", category: "Live Stream" },
  { date: "2026-07-29", title: "9:00am: Lindsay Clancy Trial", category: "Live Stream" },
  { date: "2026-07-29", title: "TBD 10:30am: Pres Trump greets the Montana State University FCS National Champions", category: "Live Stream" },
  { date: "2026-07-29", title: "VOD 2:30pm: Federal Reserve Board Chairman Kevin Warsh holds a news conference following a Federal Open Market Committee meeting", category: "Fox Nation" },
  { date: "2026-07-29", title: "9:30am: HHS Sec. Robert F. Kennedy, Jr. hosts health care leaders and behavioral health experts who pledge to strengthen the nation’s behavioral health system", category: "Live Stream" },
  { date: "2026-07-29", title: "2:00pm: Senate GOP leadership pressers.", category: "Live Stream" },
  { date: "2026-07-29", title: "3:00pm: The President makes an Announcement with the Secretary of Transportation - Oval Office", category: "Live Stream" },
  { date: "2026-07-30", title: "7:00pm: A Call to Unbreakable Courage", category: "Live Stream" },
  { date: "2026-07-30", title: "TBD 11:00am: Secretary Brooke Rollins of the U.S. Department of Agriculture, FBI Director Kash Patel, Assistant Attorney General Colin McDonald, and 40 state partners from the Southeast will participate in a roundtable and press conference", category: "Live Stream" },
  { date: "2026-07-30", title: "TBD 10:30am: White House Internship Program Class Photo", category: "Live Stream" },
  { date: "2026-07-30", title: "TBD 1:30pm: The President makes an Announcement on Freedom Haulers", category: "Live Stream" },
  { date: "2026-07-30", title: "2:00pm: News conference on upcoming U.S. Spacewalks at the International Space Station", category: "Live Stream" },
  { date: "2026-07-30", title: "TBD 3:00pm: The President participates in Signing Time - Oval Office", category: "Live Stream" },
  { date: "2026-07-31", title: "TBD 3:30pm: Kouri Richins Restitution Hearing", category: "Live Stream" },
  { date: "2026-07-31", title: "3:00pm The Weekly Rap Sheet with Paul Mauro", category: "Live Stream" },
  { date: "2026-07-31", title: "11:00am: Western Conservative Summit Morning Day 1", category: "Live Stream" },
  { date: "2026-07-31", title: "9:00pm: Western Conservative Summit Evening Day 1", category: "Live Stream" },
  { date: "2026-07-31", title: "11:00am: President Trump to host his 13th cabinet meeting of this term at Camp David", category: "Live Stream" },
  { date: "2026-08-01", title: "11:00am: Western Conservative Summit Morning Day 2", category: "Live Stream" },
  { date: "2026-08-01", title: "9:00pm: Western Conservative Summit Evening Day 2", category: "Live Stream" },
  { date: "2026-08-01", title: "A Lara Trump Interview with Sec Marco Rubio", category: "Fox Nation" },
  { date: "2026-08-01", title: "11:30am: US Senate Stump Stop with Alan Wilson, Darline Graham and others — Lexington SC", category: "Live Stream" },
  { date: "2026-08-02", title: "Live with Robert Jeffress and First Baptist Dallas (10:00 AM ET) WEEKLY", category: "Fox Nation" },
  { date: "2026-08-03", title: "Unexplained Mysteries of Faith", category: "Series,Fox Nation" },
  { date: "2026-08-03", title: "9:00am: Lindsay Clancy Trial", category: "Live Stream" },
  { date: "2026-08-03", title: "A Trey Gowdy Interview with Sen Darline Graham", category: "Fox Nation" },
  { date: "2026-08-03", title: "10:00am: Joint Task Force DC holds a virtual round table to discuss the National Guard’s contributions to the Make DC Safe and Beautiful mission", category: "Live Stream" },
  { date: "2026-08-03", title: "TBD 3:15pm: Congressman Derrick Van Orden (R-WI) will host FBI Director Kash Patel on Monday in Eau Claire, WI for a discussion with law enforcement officers from across Wisconsin’s Third Congressional District.", category: "Live Stream" },
  { date: "2026-08-03", title: "1:30pm: The President signs an Executive Order - Oval Office", category: "Live Stream" },
  { date: "2026-08-04", title: "9:00am: Senate Judiciary Committee executive business meeting to consider Todd Blanche's nomination", category: "Live Stream" },
  { date: "2026-08-04", title: "TBD 10:30pm: Trump greets the 2026 NCAA Wrestling National Champions - The Penn State Nittany Lions", category: "Live Stream" },
  { date: "2026-08-04", title: "TBD 1:00pm: The President participates in a Swearing-In Ceremony for the Director of National Intelligence -Oval Office", category: "Live Stream" },
  { date: "2026-08-04", title: "11:00am: AAG Colin McDonald of DOJ’s National Fraud Enforcement Division and senior federal officials will hold a press conference announcing a significant health care fraud takedown AND A NEW Anti-Fraud Initiative in the Eastern District of Pennsylvania.", category: "Live Stream" },
  { date: "2026-08-04", title: "2:00pm: Senate Policy Luncheon stakeout followed by Senate GOP and Dems leadership pressers", category: "Live Stream" },
  { date: "2026-08-04", title: "2:30pm: Senate Hearing: \"Your Data, Their Profit: The Consumer Cost of AI Surveillance Pricing.\"", category: "Live Stream" },
  { date: "2026-08-04", title: "3:45pm: Energy Secretary Chris Wright delivers remarks on “how American energy dominance drives economic growth” at the Port of Brownsville in Brownsville, Texas.", category: "Live Stream" },
  { date: "2026-08-04", title: "TBD 9:30pm: The President participates in a RNC roundtable", category: "Live Stream" },
  { date: "2026-08-04", title: "A Laura Ingraham Interview with Nick Shirley", category: "Fox Nation" },
  { date: "2026-08-05", title: "VOD 10:00pm: TPUSA Make Heaven Crowded Tour- PHOENIX", category: "Fox Nation" },
  { date: "2026-08-05", title: "2:30pm: Senate Hearing: \"Hidden in Plain Sight: Confronting the Muslim Brotherhood Network in America.\"", category: "Live Stream" },
  { date: "2026-08-05", title: "4:30pm: The President delivers remarks at Red Rock Casino Resort and Spa", category: "Live Stream" },
  { date: "2026-08-05", title: "A Trace Gallagher Interview with Pres Trump", category: "Fox Nation" },
  { date: "2026-08-05", title: "3:00pm: Secretary Robert F. Kennedy, Jr. press conference announcing a new health care reform action", category: "Live Stream" },
  { date: "2026-08-05", title: "10:00am: VPOTUS on-camera remarks ahead of a roundtable discussion on fraud.", category: "Live Stream" },
  { date: "2026-08-05", title: "11:00am: The Departments of Justice and State with Law Enforcement Partners press conference to announce the latest enforcement efforts to eliminate Cartel Jalisco Nueva Generación", category: "Live Stream" },
  { date: "2026-08-05", title: "A Laura Ingraham Interview with VP Vance", category: "Fox Nation" },
  { date: "2026-08-06", title: "Final Flight: The Men of Extortion 17", category: "Series,Fox Nation" },
  { date: "2026-08-06", title: "8:30am: Senate Fauci Contempt Vote", category: "Live Stream" },
  { date: "2026-08-06", title: "12:55pm: Secretary Robert F. Kennedy, Jr. visits Susan Gray Head Start alongside Administration for Children and Families Assistant Secretary Alex Adams to meet with students, educators, and administrators", category: "Live Stream" },
  { date: "2026-08-06", title: "TBD 3:00pm: The President participates in signing time", category: "Live Stream" },
  { date: "2026-08-06", title: "7:00pm: The President participates in a Team USA Reception - Rose Garden", category: "Live Stream" },
  { date: "2026-08-07", title: "COPs: Florida Man Special Season 3801-3803", category: "Series,Fox Nation" },
  { date: "2026-08-07", title: "2:00pm The Weekly Rap Sheet with Paul Mauro", category: "Live Stream" },
  { date: "2026-08-07", title: "3:00pm: President Trump hosts an American Mining Industry Roundtable at the Department of State", category: "Live Stream" },
  { date: "2026-08-08", title: "A Kayleigh McEnany Interview with VP Vance", category: "Fox Nation" },
  { date: "2026-08-08", title: "A Lara Trump Interview with Sec Mullin", category: "Fox Nation" },
  { date: "2026-08-09", title: "Live with Robert Jeffress and First Baptist Dallas (10:00 AM ET) WEEKLY", category: "Fox Nation" },
  { date: "2026-08-10", title: "Immaculate Concussion: Havana Syndrome", category: "Fox Nation" },
  { date: "2026-08-10", title: "9:00am: Lindsay Clancy Trial", category: "Live Stream" },
  { date: "2026-08-10", title: "11:00am: HHS Secretary Robert F. Kennedy, Jr. hosting major food policy celebration recognizing \"a series of landmark actions to improve the nation's food supply and advance the Make America Healthy Again agenda", category: "Live Stream" },
  { date: "2026-08-10", title: "12:20pm: Sec. Hegseth travels Monday to participate in the renaming of Joint Base Charleston to Joint Base Lindsey Graham.", category: "Live Stream" },
  { date: "2026-08-10", title: "TBD 2:00pm: Pres Trump participates in a Swearing-In Ceremony for the United States Attorney General", category: "Live Stream" },
  { date: "2026-08-10", title: "TBD 2:45pm: Pres Trump signs executive orders", category: "Live Stream" },
  { date: "2026-08-10", title: "A F&F Interview with Darline Graham", category: "Fox Nation" },
  { date: "2026-08-10", title: "4:00pm: DOJ clap-in event for AG Blanche today", category: "Live Stream" },
  { date: "2026-08-11", title: "Dirty Money with Brantley Gilbert", category: "Lifestyle" },
  { date: "2026-08-11", title: "TBD 9:00am: U.S. Transportation Secretary Sean P. Duffy and FAA Administrator Bryan Bedford will be at Newark Liberty International Airport for the installation of a new surface movement radar", category: "Live Stream" },
  { date: "2026-08-11", title: "3:50pm: Pres Trump leaves JBA for Ohio", category: "Live Stream" },
  { date: "2026-08-11", title: "TBD 7:00pm: FREEDOM 250: The President attends the 2026 Patriot Games Finale", category: "Live Stream" },
  { date: "2026-08-11", title: "11:30am: FL US Atty Gregory W. Kehoe announces arrest of foreign terror suspects", category: "Live Stream" },
  { date: "2026-08-12", title: "TBD TIME: Secretary of War Pete Hegseth will travel to Panama tomorrow to deliver remarks at the Americas Counter Cartel Coalition (A3C) Forum", category: "Live Stream" },
  { date: "2026-08-12", title: "TBD 2:30pm: Pres Trump participates in Signing Time", category: "Live Stream" },
  { date: "2026-08-12", title: "1:00pm: DOJ presser on multiple Chinese national indictments, TBD arrests", category: "Live Stream" },
  { date: "2026-08-12", title: "TBD 10:30am: The President participates in a Greeting with Law Enforcement and Military Service Members", category: "Live Stream" },
  { date: "2026-08-13", title: "GOD. FAMILY. FOOTBALL. (S3)", category: "Fox Nation" },
  { date: "2026-08-13", title: "TBD 2:00pm: Pres Trump signs Executive Orders", category: "Live Stream" },
  { date: "2026-08-13", title: "TBD 3:00pm: Pres Trump signs signing time", category: "Live Stream" },
  { date: "2026-08-13", title: "TBD 3:20pm: U.S. Department of Health and Human Services (HHS) Secretary Robert F. Kennedy, Jr. will visit Castle Family Health Centers in Atwater, California, to meet with health center leadership and announce new funding opportunities.", category: "Live Stream" },
  { date: "2026-08-13", title: "A Will Cain Interview with JD Vance", category: "Fox Nation" },
  { date: "2026-08-13", title: "11:30am: FBI Detroit Most Wanted", category: "Live Stream" },
  { date: "2026-08-14", title: "COPs: Florida Man Special Season 3804", category: "Series,Fox Nation" },
  { date: "2026-08-14", title: "3:00pm The Weekly Rap Sheet with Paul Mauro", category: "Live Stream" },
  { date: "2026-08-14", title: "10:00am: Alex Murdaugh Pretrial Hearing", category: "Live Stream" },
  { date: "2026-08-14", title: "TBD TIME: Luigi Mangione Fed Hearing Post Pressers", category: "Live Stream" },
  { date: "2026-08-14", title: "2:30pm: NASA will hold a news conference to preview a new event at NASA Kennedy later this year tied to America’s 250th anniversary", category: "Live Stream" },
  { date: "2026-08-14", title: "3:00pm: : President Trump delivers remarks at the Nassau County Police Academy Center for Training and Intelligence. Garden City, NY", category: "Live Stream" },
  { date: "2026-08-14", title: "TBD 12:00pm: The President participates in Signing Time", category: "Live Stream" },
  { date: "2026-08-15", title: "A Lara Trump Interview with Avi Loeb- UAP Advisory Council", category: "Fox Nation" },
  { date: "2026-08-15", title: "A Lara Trump Interview with FL AG James Uthmeier", category: "Fox Nation" },
  { date: "2026-08-16", title: "Live with Robert Jeffress and First Baptist Dallas (10:00 AM ET) WEEKLY", category: "Fox Nation" },
  { date: "2026-08-17", title: "The Earhart Files", category: "Special,Fox Nation" },
  { date: "2026-08-17", title: "9:00am: Lindsay Clancy Trial", category: "Live Stream" },
  { date: "2026-08-17", title: "9:30am: Justice Department holds a virtual meeting of the Religious Liberty Commission to finalize the Religious Liberty Commission report", category: "Live Stream" },
  { date: "2026-08-17", title: "TBD 11:30am: Nick Reiner Trust Hearing Post Pressers", category: "Live Stream" },
  { date: "2026-08-17", title: "12:00pm: Tupac Murder Trial", category: "Live Stream" },
  { date: "2026-08-17", title: "VOD 1:35pm: Secretary Robert F. Kennedy, Jr. will visit the Newton YMCA in Newton, IA alongside U.S. Rep. Mariannette Miller-Meeks (IA-01) to highlight efforts to improve children’s health through physical fitness, better nutrition, and strong community-based programs.", category: "Fox Nation" },
  { date: "2026-08-17", title: "TBD 1:00pm: The President greets Lifeguard Ryder Williams - Oval Office", category: "Live Stream" },
  { date: "2026-08-18", title: "10:00am: NHTSA hosts a \"Drive Sober or Get Pulled Over\" Kickoff Event", category: "Live Stream" },
  { date: "2026-08-18", title: "A Trey Yingst Interview with Jared Kushner", category: "Fox Nation" },
  { date: "2026-08-19", title: "(NEW EP) Unauthorized History Of Socialism", category: "Fox Nation" },
  { date: "2026-08-19", title: "4:00pm: Tupac Murder Trial", category: "Live Stream" },
  { date: "2026-08-19", title: "TBD 10:00am: Karmelo Anthony hearings - possible presser", category: "Live Stream" },
  { date: "2026-08-19", title: "2:30pm: The President delivers remarks with Technology Leaders - Roosevelt Room", category: "Live Stream" },
  { date: "2026-08-19", title: "1:00pm: Fairfax Presser on illegal immigrant murder arrest", category: "Live Stream" },
  { date: "2026-08-19", title: "A Will Cain Interview with Jeff Metcalf", category: "Fox Nation" },
  { date: "2026-08-20", title: "GOD. FAMILY. FOOTBALL. (S3)", category: "Fox Nation" },
  { date: "2026-08-20", title: "4:00pm: Tupac Murder Trial", category: "Live Stream" },
  { date: "2026-08-20", title: "TBD 10:00am: Karmelo Anthony hearings - possible presser", category: "Live Stream" },
  { date: "2026-08-20", title: "3:45pm: First Lady Melania Trump has a Fostering the Future press conference in the White House Rose Garden with four INDYCAR drivers", category: "Live Stream" },
  { date: "2026-08-20", title: "5:00pm: Conservative nonprofit lobbying group Texas Values is hosting a ‘Rally to Protect Women’s Sports’ in support of WNBA player Sophie Cunningham ahead of the Indiana Fever's game against the Dallas Wings. Location: Outside American Airlines Center in Dallas, TX. LIVE", category: "Live Stream" },
  { date: "2026-08-20", title: "1:00pm: Freedom 250 Grand Prix INDYCAR Media Preview on Capitol Hill race drivers.", category: "Live Stream" },
  { date: "2026-08-21", title: "COPs: Florida Man Special Season 3805", category: "Series,Fox Nation" },
  { date: "2026-08-21", title: "2:45pm: RAF12- Cleveland Press Conference", category: "Live Stream" },
  { date: "2026-08-21", title: "3:00pm The Weekly Rap Sheet with Paul Mauro", category: "Live Stream" },
  { date: "2026-08-21", title: "Behind Closed Doors: The Lindsay Clancy Case", category: "Crime" },
  { date: "2026-08-21", title: "7:00pm: Pres Trump Myrtle Beach, SC rally", category: "Live Stream" },
  { date: "2026-08-21", title: "VOD: Tupac Murder Trial", category: "Fox Nation" },
  { date: "2026-08-21", title: "1:00pm: The Vice President will travel to Cincinnati, OH for a messaging event", category: "Live Stream" },
  { date: "2026-08-21", title: "12:00pm: Secretary Robert F. Kennedy, Jr visits Rochester, Minnesota, to announce a new federal partnership focused on improving safety for autistic individuals.", category: "Live Stream" },
  { date: "2026-08-22", title: "7:45pm: RAF12- Cleveland", category: "Live Stream" },
  { date: "2026-08-22", title: "A Lara Trump Interview with Enes Kantor Freedom", category: "Fox Nation" },
  { date: "2026-08-23", title: "2:00pm: RAF Next Gen Cleveland", category: "Live Stream" },
  { date: "2026-08-23", title: "Live with Robert Jeffress and First Baptist Dallas (10:00 AM ET) WEEKLY", category: "Fox Nation" },
  { date: "2026-08-23", title: "TBD TIME: Pres Trump attends the Freedom 250 Grand Prix", category: "Live Stream" },
  { date: "2026-08-24", title: "9:00am: Lindsay Clancy Trial", category: "Live Stream" },
  { date: "2026-08-24", title: "FOX BUSINESS IN DEPTH: COURSE CORRECTION", category: "Fox Nation" },
  { date: "2026-08-24", title: "12:30pm: Tupac Murder Trial", category: "Live Stream" },
  { date: "2026-08-26", title: "Ambush at ABBEY GATE", category: "Fox Nation ,Special" },
  { date: "2026-08-27", title: "GOD. FAMILY. FOOTBALL. (S3)", category: "Fox Nation" },
  { date: "2026-08-28", title: "COPs: Season 38 Episode 6", category: "Series,Fox Nation" },
  { date: "2026-08-28", title: "3:00pm The Weekly Rap Sheet with Paul Mauro", category: "Live Stream" },
  { date: "2026-08-29", title: "TBD TIME: TPUSA Make Heaven Crowded Tour- EL PASO, TX", category: "Live Stream" },
  { date: "2026-08-29", title: "A Kayleigh McEnany Townhall with RFK Jr", category: "Fox Nation" },
  { date: "2026-08-30", title: "Live with Robert Jeffress and First Baptist Dallas (10:00 AM ET) WEEKLY", category: "Fox Nation" },
  { date: "2026-08-31", title: "Lockerbie: Justice for Pan Am 103", category: "Fox Nation ,Series" },
  { date: "2026-08-31", title: "12:30pm: Tupac Murder Trial", category: "Live Stream" },
  { date: "2026-09-01", title: "The Enemy on Campus w/ Maria Bartiromo", category: "Documentary" },
  { date: "2026-09-01", title: "12:00pm: Tyler Robinson Oral Arguments", category: "Live Stream" },
  { date: "2026-09-01", title: "TBD 7:00pm: The Murder of Charlie Kirk LIVE SHOW", category: "Live Stream" },
  { date: "2026-09-03", title: "GOD. FAMILY. FOOTBALL. (S3)", category: "Fox Nation" },
  { date: "2026-09-03", title: "Operation Homeland", category: "Fox Nation" },
  { date: "2026-09-04", title: "COPs: Season 38 Episode 7", category: "Series,Fox Nation" },
  { date: "2026-09-04", title: "Paul Mauro's Notes From Ground Zero", category: "Special" },
  { date: "2026-09-04", title: "3:00pm The Weekly Rap Sheet with Paul Mauro", category: "Live Stream" },
  { date: "2026-09-07", title: "25 Years of Tunnels to Towers", category: "Special,Fox Nation" },
  { date: "2026-09-08", title: "Born on 9/11: 25 Years With Harris Faulkner", category: "Special" },
  { date: "2026-09-09", title: "RNC Midterm Convention in Dallas, TX", category: "Live Stream" },
  { date: "2026-09-10", title: "GOD. FAMILY. FOOTBALL. (S3)", category: "Fox Nation" },
  { date: "2026-09-11", title: "COPs: Season 38 Episode 8", category: "Series,Fox Nation" },
  { date: "2026-09-11", title: "TBD: 9/11 Coverage", category: "Live Stream" },
  { date: "2026-09-13", title: "Behind the Scenes RNC with Ruthless", category: "Fox Nation" },
  { date: "2026-09-14", title: "TOXIC 2", category: "Special" },
  { date: "2026-09-16", title: "RAF Undiscovered (TBD TITLE)", category: "Fox Nation" },
  { date: "2026-09-17", title: "GOD. FAMILY. FOOTBALL. (S3)", category: "Fox Nation" },
  { date: "2026-09-17", title: "Murder on Deck 8: Who Killed Anna Kepner?", category: "Special" },
  { date: "2026-09-18", title: "2:45pm: RAF Press Conference Miami", category: "Live Stream" },
  { date: "2026-09-18", title: "COPs: Season 38 Episode 9", category: "Series,Fox Nation" },
  { date: "2026-09-18", title: "3:00pm The Weekly Rap Sheet with Paul Mauro", category: "Live Stream" },
  { date: "2026-09-19", title: "7:45pm: RAF 13 Miami", category: "Live Stream" },
  { date: "2026-09-20", title: "The Next RAF Star Live", category: "Live Stream" },
  { date: "2026-09-20", title: "TBD TIME: TPUSA Make Heaven Crowded Tour- HONOLULU, HI", category: "Live Stream" },
  { date: "2026-09-20", title: "RAF Next Gen Miami", category: "Live Stream" },
  { date: "2026-09-21", title: "Man of Honor: The Michael Monsoor", category: "Special,Fox Nation" },
  { date: "2026-09-22", title: "Stories of the American Mafia Season 3", category: "Fox Nation" },
  { date: "2026-09-23", title: "Golden State Killer: Unmasking a Monster Ep 1-4", category: "History" },
  { date: "2026-09-24", title: "TBD TIME: Pray Vote Stand Summit", category: "Live Stream" },
  { date: "2026-09-24", title: "Who is Sophie Cunningham?", category: "Fox Nation" },
  { date: "2026-09-25", title: "COPs: Season 38 Episode 10", category: "Series,Fox Nation" },
  { date: "2026-09-25", title: "2:00pm The Weekly Rap Sheet with Paul Mauro", category: "Live Stream" },
  { date: "2026-09-26", title: "Grillin' Across America", category: "Series,Fox Nation" },
  { date: "2026-09-28", title: "Chords Of Faith", category: "Special,Fox Nation" },
  { date: "2026-09-29", title: "TBD TIME: TPUSA Make Heaven Crowded Tour- CHARLOTTE, NC", category: "Live Stream" },
  { date: "2026-09-30", title: "Russia! Russia! Russia! The Plot to Stop Trump", category: "Series" },
  { date: "2026-10-02", title: "2:45pm: RAF Press Conference", category: "Live Stream" },
  { date: "2026-10-02", title: "COPs: Kansas Highway Patrol Season 38 Episode 11", category: "Series,Fox Nation" },
  { date: "2026-10-02", title: "3:00pm The Weekly Rap Sheet with Paul Mauro", category: "Live Stream" },
  { date: "2026-10-03", title: "7:45pm: RAF 14 - Vegas", category: "Live Stream" },
  // --- FOX Sports events (manual snapshot from "High Profile Sporting
  // Events" Google Sheet, Current Schedule tab, as of 2026-08-21).
  // Filtered to Network = FOX / FOXE1 / FOXE2 only. Re-upload a fresh CSV
  // export of that tab whenever the schedule changes.
  { date: "2026-08-21", title: "12:00 PM: LIV Golf - Indianapolis: Round 2", category: "FOXE1" },
  { date: "2026-08-21", title: "2:00 PM: LIV Golf - Indianapolis: Round 2", category: "FOX" },
  { date: "2026-08-21", title: "4:00 PM: Fox Noticias En Fox Deportes", category: "FOXE2" },
  { date: "2026-08-22", title: "10:30 AM: IROC Practice - Washington D.C.", category: "FOXE1" },
  { date: "2026-08-22", title: "11:00 AM: LIV Golf - Indianapolis: Round 3", category: "FOX" },
  { date: "2026-08-22", title: "12:30 PM: IROC Practice - Washington D.C.", category: "FOXE1" },
  { date: "2026-08-22", title: "1:30 PM: Saratoga Live", category: "FOXE2" },
  { date: "2026-08-22", title: "3:00 PM: Iroc Racing - Washington D.C. I", category: "FOXE1" },
  { date: "2026-08-22", title: "4:00 PM: Iroc Racing - Washington D.C. II", category: "FOXE1" },
  { date: "2026-08-22", title: "4:00 PM: AVCA First Serve - Wisconsin vs Louisville", category: "FOX" },
  { date: "2026-08-22", title: "5:00 PM: Saratoga Live", category: "FOXE2" },
  { date: "2026-08-22", title: "6:00 PM: Fox Saratoga Saturday: The Alabama Stakes", category: "FOX" },
  { date: "2026-08-22", title: "7:00 PM: Liga Dimayor Colombia - Independiente Santa Fe v América de Cali", category: "FOXE1" },
  { date: "2026-08-22", title: "7:00 PM: MLB on FOX - San Francisco Giants at Boston Red Sox", category: "FOX" },
  { date: "2026-08-22", title: "7:00 PM: MLB on FOX - Chicago Cubs at Seattle Mariners", category: "FOX" },
  { date: "2026-08-22", title: "7:00 PM: MLB on FOX - Pittsburgh Pirates at Los Angeles Dodgers", category: "FOX" },
  { date: "2026-08-23", title: "11:30 AM: INDYCAR NICS Racing Prerace - Washington D.C.", category: "FOX" },
  { date: "2026-08-23", title: "1:00 PM: INDYCAR NICS Racing - Washington D.C.", category: "FOX" },
  { date: "2026-08-23", title: "2:00 PM: Saratoga Live", category: "FOXE1" },
  { date: "2026-08-23", title: "3:30 PM: LIV Golf - Indianapolis: Round 4", category: "FOX" },
  { date: "2026-08-23", title: "8:00 PM: NFL Preseason - Seattle Seahawks at Tennessee Titans", category: "FOX" },
  { date: "2026-08-23", title: "8:00 PM: Liga MX Femenil - Club Necaxa v Club América", category: "FOXE2" },
  { date: "2026-08-23", title: "8:30 PM: Liga Profesional De Fútbol Argentino - Racing Club v Boca Juniors", category: "FOXE1" }
];

// date -> array of names on PTO that day
const SEED_PTO = {
  "2026-08-02": ["Rickey"],
  "2026-08-03": ["Rickey"],
  "2026-08-04": ["Rickey"],
  "2026-08-05": ["Dan Fillimon", "Rickey"],
  "2026-08-06": ["Rickey"],
  "2026-08-07": ["Monique", "Rickey"],
  "2026-08-08": ["Rickey"],
  "2026-08-10": ["Monique"],
  "2026-08-13": ["Monique"],
  "2026-08-14": ["Monique"],
  "2026-08-15": ["Peter B"],
  "2026-08-16": ["Peter B"],
  "2026-08-17": ["Monique"],
  "2026-08-18": ["Monique"],
  "2026-08-19": ["Monique"],
  "2026-08-21": ["Mark Schwarz"],
  "2026-08-22": ["Mark Schwarz"],
  "2026-08-23": ["Mark Schwarz"],
  "2026-08-24": ["Mark Schwarz"],
  "2026-08-25": ["Mark Schwarz"],
  "2026-08-26": ["Mark Schwarz"],
  "2026-08-28": ["Rylee"]
};

// Seed huddle notes: { "YYYY-MM-DD": { "10:00 AM": "text", "4:00 PM": "text", "8:15 PM": "text" } }
const SEED_HUDDLE_NOTES = {};

const HUDDLE_SLOTS = ["10:00 AM", "4:00 PM", "8:15 PM"];
